version: "2"

run:
  # only non-test files
  tests: false
  # base-path for skip/exclude patterns is the config file location
  relative-path-mode: cfg
  # vendor-mode for reproducible CI
  modules-download-mode: readonly

linters:
  # start with no linters enabled by default
  default: none
  enable:
    - bodyclose
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unparam
    - unused

  # any per-linter settings go here
  settings:
    # settings for gocritic
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - singleCaseSwitch
        - appendAssign
        - hugeParam
        - rangeValCopy
        - paramTypeCombine
        - unnamedResult
        - whyNoLint
        - commentedOutCode
        - docStub
        - redundantSprint
        - dynamicFmtString
        - emptyStringTest
        - builtinShadow
        - typeDefFirst

  exclusions:
    # (optional) enable built-in presets of common false positives
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    # warn about unused exclusions
    warn-unused: true
    # which paths to exclude from linting
    paths:
      - gethrpc
      - scale
      - types/metadataV[0-9]+_examplary.go
      - types/metadataV[0-9]+_examplary_string.go
    rules:
      - path: rpc/chain/subscribe_finalized_heads.go
        linters:
          - dupl
      - path: rpc/chain/subscribe_new_heads.go
        linters:
          - dupl
      - path: scale
        text: ".*" # Match any text to satisfy the requirement of at least 2 conditions
        linters:
          - dupl
          - errcheck
          - govet
      - path: types/digest.go
        linters:
          - dupl
      - path: types/digest_of.go
        linters:
          - dupl
      - path: types/int.go
        linters:
          - dupl
      - path: types/uint.go
        linters:
          - dupl
      - path: types/metadataV8.go
        linters:
          - dupl
      - path: types/metadataV10.go
        linters:
          - dupl
      - path: types/option_int.go
        linters:
          - dupl
      - path: types/option_uint.go
        linters:
          - dupl
      - path: types/data_test.go
        linters:
          - dupl
      - path: types/storage_data_raw_test.go
        linters:
          - dupl
      - path: doc.go
        linters:
          - lll
      - path: types/example_tuple_test.go
        linters:
          - lll
      - path: types/junction_v3.go
        linters:
          - gofmt
          - goimports
      - path: types/network_id.go
        linters:
          - gofmt
          - goimports
      - path: types/extrinsic_mode.go
        linters:
          - goimports
      - text: "G115: integer overflow conversion"
        linters:
          - gosec
      - path: types/extrinsic_status.go
        linters:
          - staticcheck

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: false
    goimports:
      # e.g. to group your imports
      local-prefixes:
        - github.com/yourorg/yourrepo
