services:
  substrate:
    container_name: substrate
    image: moonbeamfoundation/moonbeam:v0.44
    platform: linux/amd64
    ports:
      - 9933:9933
      - 9944:9944
      - 30333:30333
    command: --dev --rpc-external --rpc-methods Unsafe --offchain-worker Always --sealing 1000
  gsrpc-test:
    image: gsrpc-test
    build: .
    environment:
      - RPC_URL=ws://substrate:9944
      - TEST_PRIV_KEY=//Alice
    volumes:
      - "$PWD:/go-substrate-rpc-client"
